name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what did you expect?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Steps to reproduce
      placeholder: "1. Go to...\n2. Click...\n3. See error..."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version/Commit
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell
