name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package.json
        id: detect
        run: |
          if [ -f package.json ]; then echo "found=true" >> $GITHUB_OUTPUT; else echo "found=false" >> $GITHUB_OUTPUT; fi

      - name: Setup Node
        if: steps.detect.outputs.found == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        if: steps.detect.outputs.found == 'true'
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        if: steps.detect.outputs.found == 'true'
        run: pnpm i --frozen-lockfile || pnpm i

      - name: Typecheck
        if: steps.detect.outputs.found == 'true'
        run: pnpm run -s typecheck || echo "typecheck placeholder"

      - name: Lint
        if: steps.detect.outputs.found == 'true'
        run: pnpm run -s lint || echo "lint placeholder"

      - name: Unit tests
        if: steps.detect.outputs.found == 'true'
        run: pnpm run -s test || echo "tests placeholder"

      - name: Build
        if: steps.detect.outputs.found == 'true'
        run: pnpm run -s build || echo "build placeholder"
