name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect package.json
        id: detect
        run: |
          if [ -f package.json ]; then echo "found=true" >> $GITHUB_OUTPUT; else echo "found=false" >> $GITHUB_OUTPUT; fi

      - name: Setup Node
        if: steps.detect.outputs.found == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        if: steps.detect.outputs.found == 'true'
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        if: steps.detect.outputs.found == 'true'
        run: pnpm i --frozen-lockfile || pnpm i

      - name: Semantic Release
        if: steps.detect.outputs.found == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
