name: ZAP Baseline

"on":
  pull_request:
    branches: [ main ]

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:3000'
        continue-on-error: true
